classdef Parameters < magicformula.Parameters
    %PARAMETERS Magic Formula 6.1.2 parameter set.
    % Parameter names implemented according to:
    %   https://functionbay.com/documentation/onlinehelp/Documents/Tire/MFTyre-MFSwift_Help.pdf
    %
    properties
        %% [MODEL]
        FITTYP                  magicformula.Parameter = magicformula.Parameter('FITTYP', 61)
        TYRESIDE                magicformula.Parameter = magicformula.Parameter('TYRESIDE', 'LEFT')
        LONGVL                  magicformula.Parameter = magicformula.Parameter('LONGVL', 10)
        VXLOW                   magicformula.Parameter = magicformula.Parameter('VXLOW', 1)
        ROAD_INCREMENT          magicformula.Parameter = magicformula.Parameter('ROAD_INCREMENT')
        ROAD_DIRECTION          magicformula.Parameter = magicformula.Parameter('ROAD_DIRECTION')
        %% [DIMENSION]
        UNLOADED_RADIUS         magicformula.Parameter = magicformula.Parameter('UNLOADED_RADIUS')
        WIDTH                   magicformula.Parameter = magicformula.Parameter('WIDTH')
        RIM_RADIUS              magicformula.Parameter = magicformula.Parameter('RIM_RADIUS')
        RIM_WIDTH               magicformula.Parameter = magicformula.Parameter('RIM_WIDTH')
        ASPECT_RATIO            magicformula.Parameter = magicformula.Parameter('ASPECT_RATIO')
        %% [OPERATING_CONDITIONS]
        INFLPRES                magicformula.Parameter = magicformula.Parameter('INFLPRES')
        NOMPRES                 magicformula.Parameter = magicformula.Parameter('NOMPRES', 1E5)
        %% [INERTIA]
        MASS                    magicformula.Parameter = magicformula.Parameter('MASS')
        IXX                     magicformula.Parameter = magicformula.Parameter('IXX')
        IYY                     magicformula.Parameter = magicformula.Parameter('IYY')
        BELT_IXX                magicformula.Parameter = magicformula.Parameter('BELT_IXX')
        BELT_IYY                magicformula.Parameter = magicformula.Parameter('BELT_IYY')
        BELT_MASS               magicformula.Parameter = magicformula.Parameter('BELT_MASS')
        GRAVITY                 magicformula.Parameter = magicformula.Parameter('GRAVITY')
        %% [VERTICAL]
        FNOMIN                  magicformula.Parameter = magicformula.Parameter('FNOMIN', 1500)
        VERTICAL_DAMPING        magicformula.Parameter = magicformula.Parameter('VERTICAL_DAMPING')
        VERTICAL_STIFFNESS      magicformula.Parameter = magicformula.Parameter('VERTICAL_STIFFNESS')
        MC_CONTOUR_A            magicformula.Parameter = magicformula.Parameter('MC_CONTOUR_A')
        MC_CONTOUR_B            magicformula.Parameter = magicformula.Parameter('MC_CONTOUR_B')
        BREFF                   magicformula.Parameter = magicformula.Parameter('BREFF')
        DREFF                   magicformula.Parameter = magicformula.Parameter('DREFF')
        FREFF                   magicformula.Parameter = magicformula.Parameter('FREFF')
        Q_RE0                   magicformula.Parameter = magicformula.Parameter('Q_RE0')
        Q_V1                    magicformula.Parameter = magicformula.Parameter('Q_V1')
        Q_V2                    magicformula.Parameter = magicformula.Parameter('Q_V2')
        Q_FZ2                   magicformula.Parameter = magicformula.Parameter('Q_FZ2')
        Q_FCX                   magicformula.Parameter = magicformula.Parameter('Q_FCX')
        Q_FCY                   magicformula.Parameter = magicformula.Parameter('Q_FCY')
        Q_FCY2                  magicformula.Parameter = magicformula.Parameter('Q_FCY2')
        Q_CAM                   magicformula.Parameter = magicformula.Parameter('Q_CAM')
        Q_CAM1                  magicformula.Parameter = magicformula.Parameter('Q_CAM1')
        Q_CAM2                  magicformula.Parameter = magicformula.Parameter('Q_CAM2')
        Q_CAM3                  magicformula.Parameter = magicformula.Parameter('Q_CAM3')
        Q_FYS1                  magicformula.Parameter = magicformula.Parameter('Q_FYS1')
        Q_FYS2                  magicformula.Parameter = magicformula.Parameter('Q_FYS2')
        Q_FYS3                  magicformula.Parameter = magicformula.Parameter('Q_FYS3')
        PFZ1                    magicformula.Parameter = magicformula.Parameter('PFZ1')
        BOTTOM_OFFST            magicformula.Parameter = magicformula.Parameter('BOTTOM_OFFST')
        BOTTOM_STIFF            magicformula.Parameter = magicformula.Parameter('BOTTOM_STIFF')
        %% [STRUCTURAL]
        LONGITUDINAL_STIFFNESS  magicformula.Parameter = magicformula.Parameter('LONGITUDINAL_STIFFNESS')
        LATERAL_STIFFNESS       magicformula.Parameter = magicformula.Parameter('LATERAL_STIFFNESS')
        YAW_STIFFNESS           magicformula.Parameter = magicformula.Parameter('YAW_STIFFNESS')
        FREQ_LAT                magicformula.Parameter = magicformula.Parameter('FREQ_LAT')
        FREQ_LONG               magicformula.Parameter = magicformula.Parameter('FREQ_LONG')
        FREQ_WINDUP             magicformula.Parameter = magicformula.Parameter('FREQ_WINDUP')
        FREQ_YAW                magicformula.Parameter = magicformula.Parameter('FREQ_YAW')
        DAMP_LAT                magicformula.Parameter = magicformula.Parameter('DAMP_LAT')
        DAMP_LONG               magicformula.Parameter = magicformula.Parameter('DAMP_LONG')
        DAMP_RESIDUAL           magicformula.Parameter = magicformula.Parameter('DAMP_RESIDUAL')
        DAMP_VLOW               magicformula.Parameter = magicformula.Parameter('DAMP_VLOW')
        DAMP_WINDUP             magicformula.Parameter = magicformula.Parameter('DAMP_WINDUP')
        DAMP_YAW                magicformula.Parameter = magicformula.Parameter('DAMP_YAW')
        Q_BVX                   magicformula.Parameter = magicformula.Parameter('Q_BVX')
        Q_BVT                   magicformula.Parameter = magicformula.Parameter('Q_BVT')
        PCFX1                   magicformula.Parameter = magicformula.Parameter('PCFX1')
        PCFX2                   magicformula.Parameter = magicformula.Parameter('PCFX2')
        PCFX3                   magicformula.Parameter = magicformula.Parameter('PCFX3')
        PCFY1                   magicformula.Parameter = magicformula.Parameter('PCFY1')
        PCFY2                   magicformula.Parameter = magicformula.Parameter('PCFY2')
        PCFY3                   magicformula.Parameter = magicformula.Parameter('PCFY3')
        PCMZ1                   magicformula.Parameter = magicformula.Parameter('PCMZ1')
        %% [CONTACT_PATCH]
        Q_RA1                   magicformula.Parameter = magicformula.Parameter('Q_RA1')
        Q_RA2                   magicformula.Parameter = magicformula.Parameter('Q_RA2')
        Q_RB1                   magicformula.Parameter = magicformula.Parameter('Q_RB1')
        Q_RB2                   magicformula.Parameter = magicformula.Parameter('Q_RB2')
        ELLIPS_SHIFT            magicformula.Parameter = magicformula.Parameter('ELLIPS_SHIFT')
        ELLIPS_LENGTH           magicformula.Parameter = magicformula.Parameter('ELLIPS_LENGTH')
        ELLIPS_HEIGHT           magicformula.Parameter = magicformula.Parameter('ELLIPS_HEIGHT')
        ELLIPS_ORDER            magicformula.Parameter = magicformula.Parameter('ELLIPS_ORDER')
        ELLIPS_MAX_STEP         magicformula.Parameter = magicformula.Parameter('ELLIPS_MAX_STEP')
        ELLIPS_NWIDTH           magicformula.Parameter = magicformula.Parameter('ELLIPS_NWIDTH')
        ELLIPS_NLENGTH          magicformula.Parameter = magicformula.Parameter('ELLIPS_NLENGTH')
        ENV_C1                  magicformula.Parameter = magicformula.Parameter('ENV_C1')
        ENV_C2                  magicformula.Parameter = magicformula.Parameter('ENV_C2')
        Q_A1                    magicformula.Parameter = magicformula.Parameter('Q_A1')
        Q_A2                    magicformula.Parameter = magicformula.Parameter('Q_A2')
        %% [INFLATION_PRESSURE_RANGE]
        PRESMIN                 magicformula.Parameter = magicformula.Parameter('PRESMIN')
        PRESMAX                 magicformula.Parameter = magicformula.Parameter('PRESMAX')
        %% [VERTICAL_FORCE_RANGE]
        FZMAX                   magicformula.Parameter = magicformula.Parameter('FZMAX')
        FZMIN                   magicformula.Parameter = magicformula.Parameter('FZMIN')
        %% [LONG_SLIP_RANGE]
        KPUMIN                  magicformula.Parameter = magicformula.Parameter('KPUMIN')
        KPUMAX                  magicformula.Parameter = magicformula.Parameter('KPUMAX')
        %% [SLIP_ANGLE_RANGE]
        ALPMIN                  magicformula.Parameter = magicformula.Parameter('ALPMIN')
        ALPMAX                  magicformula.Parameter = magicformula.Parameter('ALPMAX')
        %% [INCLINATION_ANGLE_RANGE]
        CAMMIN                  magicformula.Parameter = magicformula.Parameter('CAMMIN')
        CAMMAX                  magicformula.Parameter = magicformula.Parameter('CAMMAX')
        %% [SCALING_COEFFICIENTS]
        LFZO                    magicformula.Parameter = magicformula.Parameter('LFZO', 1)
        LCX                     magicformula.Parameter = magicformula.Parameter('LCX', 1)
        LMUX                    magicformula.Parameter = magicformula.Parameter('LMUX', 1)
        LEX                     magicformula.Parameter = magicformula.Parameter('LEX', 1)
        LKX                     magicformula.Parameter = magicformula.Parameter('LKX', 1)
        LHX                     magicformula.Parameter = magicformula.Parameter('LHX', 1)
        LVX                     magicformula.Parameter = magicformula.Parameter('LVX', 1)
        LCY                     magicformula.Parameter = magicformula.Parameter('LCY', 1)
        LMUY                    magicformula.Parameter = magicformula.Parameter('LMUY', 1)
        LEY                     magicformula.Parameter = magicformula.Parameter('LEY', 1)
        LKY                     magicformula.Parameter = magicformula.Parameter('LKY', 1)
        LKYC                    magicformula.Parameter = magicformula.Parameter('LKYC', 1)
        LKZC                    magicformula.Parameter = magicformula.Parameter('LKZC', 1)
        LHY                     magicformula.Parameter = magicformula.Parameter('LHY', 1)
        LVY                     magicformula.Parameter = magicformula.Parameter('LVY', 1)
        LTR                     magicformula.Parameter = magicformula.Parameter('LTR', 1)
        LRES                    magicformula.Parameter = magicformula.Parameter('LRES', 1)
        LXAL                    magicformula.Parameter = magicformula.Parameter('LXAL', 1)
        LYKA                    magicformula.Parameter = magicformula.Parameter('LYKA', 1)
        LVYKA                   magicformula.Parameter = magicformula.Parameter('LVYKA', 1)
        LS                      magicformula.Parameter = magicformula.Parameter('LS', 1)
        LMX                     magicformula.Parameter = magicformula.Parameter('LMX', 1)
        LVMX                    magicformula.Parameter = magicformula.Parameter('LVMX', 1)
        LMY                     magicformula.Parameter = magicformula.Parameter('LMY', 1)
        LMP                     magicformula.Parameter = magicformula.Parameter('LMP', 1)
        %% [LONGITUDINAL_COEFFICIENTS]
        PCX1                    magicformula.Parameter = magicformula.ParameterFittable('PCX1', 1.9, 1.5, inf)
        PDX1                    magicformula.Parameter = magicformula.ParameterFittable('PDX1', 2, 1, 5)
        PDX2                    magicformula.Parameter = magicformula.ParameterFittable('PDX2', -0.01, -1, 0)
        PDX3                    magicformula.Parameter = magicformula.ParameterFittable('PDX3', 10, 0, 15)
        PEX1                    magicformula.Parameter = magicformula.ParameterFittable('PEX1', -1, -100, 0)
        PEX2                    magicformula.Parameter = magicformula.ParameterFittable('PEX2', 0.3, -3, 3)
        PEX3                    magicformula.Parameter = magicformula.ParameterFittable('PEX3', 0, -0.6, 0.6)
        PEX4                    magicformula.Parameter = magicformula.ParameterFittable('PEX4', 0, -0.9, 0.9)
        PKX1                    magicformula.Parameter = magicformula.ParameterFittable('PKX1', 20, 5, 100)
        PKX2                    magicformula.Parameter = magicformula.ParameterFittable('PKX2', 10, -30, 30)
        PKX3                    magicformula.Parameter = magicformula.ParameterFittable('PKX3', 0, -10, 10)
        PHX1                    magicformula.Parameter = magicformula.ParameterFittable('PHX1', 0, -0.1, 0.1)
        PHX2                    magicformula.Parameter = magicformula.ParameterFittable('PHX2', 0, -0.1, 0.1)
        PVX1                    magicformula.Parameter = magicformula.ParameterFittable('PVX1', 0, -0.1, 0.1)
        PVX2                    magicformula.Parameter = magicformula.ParameterFittable('PVX2', 0, -0.1, 0.1)
        RBX1                    magicformula.Parameter = magicformula.ParameterFittable('RBX1', 5, 5, 50)
        RBX2                    magicformula.Parameter = magicformula.ParameterFittable('RBX2', 5, 5, 50)
        RBX3                    magicformula.Parameter = magicformula.ParameterFittable('RBX3')
        RCX1                    magicformula.Parameter = magicformula.ParameterFittable('RCX1', 1, -1, 1.2)
        REX1                    magicformula.Parameter = magicformula.ParameterFittable('REX1', -1, -10, 1)
        REX2                    magicformula.Parameter = magicformula.ParameterFittable('REX2', -0.1, -5, 1)
        RHX1                    magicformula.Parameter = magicformula.ParameterFittable('RHX1')
        PPX1                    magicformula.Parameter = magicformula.ParameterFittable('PPX1')
        PPX2                    magicformula.Parameter = magicformula.ParameterFittable('PPX2')
        PPX3                    magicformula.Parameter = magicformula.ParameterFittable('PPX3')
        PPX4                    magicformula.Parameter = magicformula.ParameterFittable('PPX4')
        %% [OVERTURNING_COEFFICIENTS]
        QSX1                    magicformula.Parameter = magicformula.ParameterFittable('QSX1')
        QSX2                    magicformula.Parameter = magicformula.ParameterFittable('QSX2', 1.5)
        QSX3                    magicformula.Parameter = magicformula.ParameterFittable('QSX3', 0.1)
        QSX4                    magicformula.Parameter = magicformula.ParameterFittable('QSX4', 0.1)
        QSX5                    magicformula.Parameter = magicformula.ParameterFittable('QSX5')
        QSX6                    magicformula.Parameter = magicformula.ParameterFittable('QSX6')
        QSX7                    magicformula.Parameter = magicformula.ParameterFittable('QSX7', 0.1)
        QSX8                    magicformula.Parameter = magicformula.ParameterFittable('QSX8')
        QSX9                    magicformula.Parameter = magicformula.ParameterFittable('QSX9')
        QSX10                   magicformula.Parameter = magicformula.ParameterFittable('QSX10')
        QSX11                   magicformula.Parameter = magicformula.ParameterFittable('QSX11')
        QSX12                   magicformula.Parameter = magicformula.ParameterFittable('QSX12', 0, -inf, inf, true)
        QSX13                   magicformula.Parameter = magicformula.ParameterFittable('QSX13', 0, -inf, inf, true)
        QSX14                   magicformula.Parameter = magicformula.ParameterFittable('QSX14', 0, -inf, inf, true)
        PPMX1                   magicformula.Parameter = magicformula.ParameterFittable('PPMX1')
        %% [LATERAL_COEFFICIENTS]
        PCY1                    magicformula.Parameter = magicformula.ParameterFittable('PCY1', 2, 1.5, 5)
        PDY1                    magicformula.Parameter = magicformula.ParameterFittable('PDY1', 0.8, 0.1, 5)
        PDY2                    magicformula.Parameter = magicformula.ParameterFittable('PDY2', -0.05, -0.5, 0)
        PDY3                    magicformula.Parameter = magicformula.ParameterFittable('PDY3', 0, -10, 10)
        PEY1                    magicformula.Parameter = magicformula.ParameterFittable('PEY1', -0.8, -100, 100)
        PEY2                    magicformula.Parameter = magicformula.ParameterFittable('PEY2', -0.6, -100, 100)
        PEY3                    magicformula.Parameter = magicformula.ParameterFittable('PEY3', 0.1)
        PEY4                    magicformula.Parameter = magicformula.ParameterFittable('PEY4')
        PEY5                    magicformula.Parameter = magicformula.ParameterFittable('PEY5')
        PKY1                    magicformula.Parameter = magicformula.ParameterFittable('PKY1', -20, -100, -5)
        PKY2                    magicformula.Parameter = magicformula.ParameterFittable('PKY2', 2, -5, 5)
        PKY3                    magicformula.Parameter = magicformula.ParameterFittable('PKY3', 0, -1, 1)
        PKY4                    magicformula.Parameter = magicformula.ParameterFittable('PKY4', 2, 1.05, 2, true)
        PKY5                    magicformula.Parameter = magicformula.ParameterFittable('PKY5')
        PKY6                    magicformula.Parameter = magicformula.ParameterFittable('PKY6')
        PKY7                    magicformula.Parameter = magicformula.ParameterFittable('PKY7')
        PHY1                    magicformula.Parameter = magicformula.ParameterFittable('PHY1')
        PHY2                    magicformula.Parameter = magicformula.ParameterFittable('PHY2')
        PVY1                    magicformula.Parameter = magicformula.ParameterFittable('PVY1')
        PVY2                    magicformula.Parameter = magicformula.ParameterFittable('PVY2')
        PVY3                    magicformula.Parameter = magicformula.ParameterFittable('PVY3')
        PVY4                    magicformula.Parameter = magicformula.ParameterFittable('PVY4')
        RBY1                    magicformula.Parameter = magicformula.ParameterFittable('RBY1', 5, 2, 40)
        RBY2                    magicformula.Parameter = magicformula.ParameterFittable('RBY2', 2, 2, 40)
        RBY3                    magicformula.Parameter = magicformula.ParameterFittable('RBY3', 0.02, -0.15, 0.15)
        RBY4                    magicformula.Parameter = magicformula.ParameterFittable('RBY4', 0, -90, 90)
        RCY1                    magicformula.Parameter = magicformula.ParameterFittable('RCY1', 1, 0.8, 5)
        REY1                    magicformula.Parameter = magicformula.ParameterFittable('REY1', -0.1, -6, 1)
        REY2                    magicformula.Parameter = magicformula.ParameterFittable('REY2', 0.1, -1, 5)
        RHY1                    magicformula.Parameter = magicformula.ParameterFittable('RHY1')
        RHY2                    magicformula.Parameter = magicformula.ParameterFittable('RHY2')
        RVY1                    magicformula.Parameter = magicformula.ParameterFittable('RVY1')
        RVY2                    magicformula.Parameter = magicformula.ParameterFittable('RVY2')
        RVY3                    magicformula.Parameter = magicformula.ParameterFittable('RVY3')
        RVY4                    magicformula.Parameter = magicformula.ParameterFittable('RVY4')
        RVY5                    magicformula.Parameter = magicformula.ParameterFittable('RVY5')
        RVY6                    magicformula.Parameter = magicformula.ParameterFittable('RVY6')
        PPY1                    magicformula.Parameter = magicformula.ParameterFittable('PPY1', 0.1, -2, 2)
        PPY2                    magicformula.Parameter = magicformula.ParameterFittable('PPY2', 0.1, -2, 2)
        PPY3                    magicformula.Parameter = magicformula.ParameterFittable('PPY3', 0, -2, 1)
        PPY4                    magicformula.Parameter = magicformula.ParameterFittable('PPY4', 0, -2, 1)
        PPY5                    magicformula.Parameter = magicformula.ParameterFittable('PPY5')
        %% [ROLLING_COEFFICIENTS]
        QSY1                    magicformula.Parameter = magicformula.ParameterFittable('QSY1')
        QSY2                    magicformula.Parameter = magicformula.ParameterFittable('QSY2')
        QSY3                    magicformula.Parameter = magicformula.ParameterFittable('QSY3')
        QSY4                    magicformula.Parameter = magicformula.ParameterFittable('QSY4')
        QSY5                    magicformula.Parameter = magicformula.ParameterFittable('QSY5')
        QSY6                    magicformula.Parameter = magicformula.ParameterFittable('QSY6')
        QSY7                    magicformula.Parameter = magicformula.ParameterFittable('QSY7')
        QSY8                    magicformula.Parameter = magicformula.ParameterFittable('QSY8')
        %% [ALIGNING_COEFFICIENTS]
        QBZ1                    magicformula.Parameter = magicformula.ParameterFittable('QBZ1', eps())
        QBZ2                    magicformula.Parameter = magicformula.ParameterFittable('QBZ2')
        QBZ3                    magicformula.Parameter = magicformula.ParameterFittable('QBZ3')
        QBZ4                    magicformula.Parameter = magicformula.ParameterFittable('QBZ4')
        QBZ5                    magicformula.Parameter = magicformula.ParameterFittable('QBZ5')
        QBZ9                    magicformula.Parameter = magicformula.ParameterFittable('QBZ9')
        QBZ10                   magicformula.Parameter = magicformula.ParameterFittable('QBZ10')
        QCZ1                    magicformula.Parameter = magicformula.ParameterFittable('QCZ1', 0.1, eps(), inf)
        QDZ1                    magicformula.Parameter = magicformula.ParameterFittable('QDZ1', 0.1, eps(), inf)
        QDZ2                    magicformula.Parameter = magicformula.ParameterFittable('QDZ2')
        QDZ3                    magicformula.Parameter = magicformula.ParameterFittable('QDZ3')
        QDZ4                    magicformula.Parameter = magicformula.ParameterFittable('QDZ4')
        QDZ6                    magicformula.Parameter = magicformula.ParameterFittable('QDZ6')
        QDZ7                    magicformula.Parameter = magicformula.ParameterFittable('QDZ7')
        QDZ8                    magicformula.Parameter = magicformula.ParameterFittable('QDZ8')
        QDZ9                    magicformula.Parameter = magicformula.ParameterFittable('QDZ9')
        QDZ10                   magicformula.Parameter = magicformula.ParameterFittable('QDZ10')
        QDZ11                   magicformula.Parameter = magicformula.ParameterFittable('QDZ11')
        QEZ1                    magicformula.Parameter = magicformula.ParameterFittable('QEZ1')
        QEZ2                    magicformula.Parameter = magicformula.ParameterFittable('QEZ2')
        QEZ3                    magicformula.Parameter = magicformula.ParameterFittable('QEZ3')
        QEZ4                    magicformula.Parameter = magicformula.ParameterFittable('QEZ4')
        QEZ5                    magicformula.Parameter = magicformula.ParameterFittable('QEZ5')
        QHZ1                    magicformula.Parameter = magicformula.ParameterFittable('QHZ1')
        QHZ2                    magicformula.Parameter = magicformula.ParameterFittable('QHZ2')
        QHZ3                    magicformula.Parameter = magicformula.ParameterFittable('QHZ3')
        QHZ4                    magicformula.Parameter = magicformula.ParameterFittable('QHZ4')
        SSZ1                    magicformula.Parameter = magicformula.ParameterFittable('SSZ1')
        SSZ2                    magicformula.Parameter = magicformula.ParameterFittable('SSZ2')
        SSZ3                    magicformula.Parameter = magicformula.ParameterFittable('SSZ3')
        SSZ4                    magicformula.Parameter = magicformula.ParameterFittable('SSZ4')
        PPZ1                    magicformula.Parameter = magicformula.ParameterFittable('PPZ1')
        PPZ2                    magicformula.Parameter = magicformula.ParameterFittable('PPZ2')
        %% [TURNSLIP_COEFFICIENTS]
        PDXP1                   magicformula.Parameter = magicformula.ParameterFittable('PDXP1')
        PDXP2                   magicformula.Parameter = magicformula.ParameterFittable('PDXP2')
        PDXP3                   magicformula.Parameter = magicformula.ParameterFittable('PDXP3')
        PKYP1                   magicformula.Parameter = magicformula.ParameterFittable('PKYP1')
        PDYP1                   magicformula.Parameter = magicformula.ParameterFittable('PDYP1')
        PDYP2                   magicformula.Parameter = magicformula.ParameterFittable('PDYP2')
        PDYP3                   magicformula.Parameter = magicformula.ParameterFittable('PDYP3')
        PDYP4                   magicformula.Parameter = magicformula.ParameterFittable('PDYP4')
        PHYP1                   magicformula.Parameter = magicformula.ParameterFittable('PHYP1')
        PHYP2                   magicformula.Parameter = magicformula.ParameterFittable('PHYP2')
        PHYP3                   magicformula.Parameter = magicformula.ParameterFittable('PHYP3')
        PHYP4                   magicformula.Parameter = magicformula.ParameterFittable('PHYP4')
        PECP1                   magicformula.Parameter = magicformula.ParameterFittable('PECP1')
        PECP2                   magicformula.Parameter = magicformula.ParameterFittable('PECP2')
        QDTP1                   magicformula.Parameter = magicformula.ParameterFittable('QDTP1')
        QCRP1                   magicformula.Parameter = magicformula.ParameterFittable('QCRP1')
        QCRP2                   magicformula.Parameter = magicformula.ParameterFittable('QCRP2')
        QBRP1                   magicformula.Parameter = magicformula.ParameterFittable('QBRP1')
        QDRP1                   magicformula.Parameter = magicformula.ParameterFittable('QDRP1')
    end
end

