classdef (Hidden) Parameters < magicformula.Parameters
    %PARAMETERS Magic Formula 5.2 parameter set.
    % Parameter names implemented according to:
    %   https://functionbay.com/documentation/onlinehelp/Documents/Tire/MFTyre-MFSwift_Help.pdf
    %
    properties
        %% [MODEL]
        FITTYP                  magicformula.Parameter = magicformula.Parameter('FITTYP', 6)
        TYRESIDE                magicformula.Parameter = magicformula.Parameter('TYRESIDE', 'LEFT')
        LONGVL                  magicformula.Parameter = magicformula.Parameter('LONGVL')
        VXLOW                   magicformula.Parameter = magicformula.Parameter('VXLOW')
        ROAD_INCREMENT          magicformula.Parameter = magicformula.Parameter('ROAD_INCREMENT')
        ROAD_DIRECTION          magicformula.Parameter = magicformula.Parameter('ROAD_DIRECTION')
        %% [DIMENSION]
        UNLOADED_RADIUS         magicformula.Parameter = magicformula.Parameter('UNLOADED_RADIUS')
        WIDTH                   magicformula.Parameter = magicformula.Parameter('WIDTH')
        RIM_RADIUS              magicformula.Parameter = magicformula.Parameter('RIM_RADIUS')
        RIM_WIDTH               magicformula.Parameter = magicformula.Parameter('RIM_WIDTH')
        ASPECT_RATIO            magicformula.Parameter = magicformula.Parameter('ASPECT_RATIO')
        %% [VERTICAL]
        FNOMIN                  magicformula.Parameter = magicformula.Parameter('FNOMIN', 1500)
        VERTICAL_DAMPING        magicformula.Parameter = magicformula.Parameter('VERTICAL_DAMPING')
        VERTICAL_STIFFNESS      magicformula.Parameter = magicformula.Parameter('VERTICAL_STIFFNESS')
        BREFF                   magicformula.Parameter = magicformula.Parameter('BREFF')
        DREFF                   magicformula.Parameter = magicformula.Parameter('DREFF')
        FREFF                   magicformula.Parameter = magicformula.Parameter('FREFF')
        %% [VERTICAL_FORCE_RANGE]
        FZMAX                   magicformula.Parameter = magicformula.Parameter('FZMAX')
        FZMIN                   magicformula.Parameter = magicformula.Parameter('FZMIN')
        %% [LONG_SLIP_RANGE]
        KPUMIN                  magicformula.Parameter = magicformula.Parameter('KPUMIN')
        KPUMAX                  magicformula.Parameter = magicformula.Parameter('KPUMAX')
        %% [SLIP_ANGLE_RANGE]
        ALPMIN                  magicformula.Parameter = magicformula.Parameter('ALPMIN')
        ALPMAX                  magicformula.Parameter = magicformula.Parameter('ALPMAX')
        %% [INCLINATION_ANGLE_RANGE]
        CAMMIN                  magicformula.Parameter = magicformula.Parameter('CAMMIN')
        CAMMAX                  magicformula.Parameter = magicformula.Parameter('CAMMAX')
        %% [SCALING_COEFFICIENTS]
        LFZO                    magicformula.Parameter = magicformula.ParameterFittable('LFZO', 1)
        LCX                     magicformula.Parameter = magicformula.ParameterFittable('LCX', 1)
        LMUX                    magicformula.Parameter = magicformula.ParameterFittable('LMUX', 1)
        LEX                     magicformula.Parameter = magicformula.ParameterFittable('LEX', 1)
        LKX                     magicformula.Parameter = magicformula.ParameterFittable('LKX', 1)
        LHX                     magicformula.Parameter = magicformula.ParameterFittable('LHX', 1)
        LVX                     magicformula.Parameter = magicformula.ParameterFittable('LVX', 1)
        LCY                     magicformula.Parameter = magicformula.ParameterFittable('LCY', 1)
        LMUY                    magicformula.Parameter = magicformula.ParameterFittable('LMUY', 1)
        LEY                     magicformula.Parameter = magicformula.ParameterFittable('LEY', 1)
        LKY                     magicformula.Parameter = magicformula.ParameterFittable('LKY', 1)
        LHY                     magicformula.Parameter = magicformula.ParameterFittable('LHY', 1)
        LVY                     magicformula.Parameter = magicformula.ParameterFittable('LVY', 1)
        LTR                     magicformula.Parameter = magicformula.ParameterFittable('LTR', 1)
        LRES                    magicformula.Parameter = magicformula.ParameterFittable('LRES', 1)
        LXAL                    magicformula.Parameter = magicformula.ParameterFittable('LXAL', 1)
        LYKA                    magicformula.Parameter = magicformula.ParameterFittable('LYKA', 1)
        LVYKA                   magicformula.Parameter = magicformula.ParameterFittable('LVYKA', 1)
        LS                      magicformula.Parameter = magicformula.ParameterFittable('LS', 1)
        LMX                     magicformula.Parameter = magicformula.ParameterFittable('LMX', 1)
        LVMX                    magicformula.Parameter = magicformula.ParameterFittable('LVMX', 1)
        LMY                     magicformula.Parameter = magicformula.ParameterFittable('LMY', 1)
        LSGKP   	            magicformula.Parameter = magicformula.ParameterFittable('LSGKP', 1)
        LSGAL   	            magicformula.Parameter = magicformula.ParameterFittable('LSGAL', 1)
        LGYR                    magicformula.Parameter = magicformula.ParameterFittable('LGYR', 1)
        %% [LONGITUDINAL_COEFFICIENTS]
        PCX1                    magicformula.Parameter = magicformula.ParameterFittable('PCX1', 1.9, 1.5, 2)
        PDX1                    magicformula.Parameter = magicformula.ParameterFittable('PDX1', 2, 1, 5)
        PDX2                    magicformula.Parameter = magicformula.ParameterFittable('PDX2', -0.01, -1, 0)
        PDX3                    magicformula.Parameter = magicformula.ParameterFittable('PDX3', 10, 0, 15)
        PEX1                    magicformula.Parameter = magicformula.ParameterFittable('PEX1', -1, -100, 0)
        PEX2                    magicformula.Parameter = magicformula.ParameterFittable('PEX2', 0.3, -3, 3)
        PEX3                    magicformula.Parameter = magicformula.ParameterFittable('PEX3', 0, -0.6, 0.6, true)
        PEX4                    magicformula.Parameter = magicformula.ParameterFittable('PEX4', 0, -0.9, 0.9, true)
        PKX1                    magicformula.Parameter = magicformula.ParameterFittable('PKX1', 20, 5, 100)
        PKX2                    magicformula.Parameter = magicformula.ParameterFittable('PKX2', 10, -30, 30)
        PKX3                    magicformula.Parameter = magicformula.ParameterFittable('PKX3', 0, -10, 10)
        PHX1                    magicformula.Parameter = magicformula.ParameterFittable('PHX1', 0, -0.1, 0.1)
        PHX2                    magicformula.Parameter = magicformula.ParameterFittable('PHX2', 0, -0.1, 0.1)
        PVX1                    magicformula.Parameter = magicformula.ParameterFittable('PVX1', 0, -0.1, 0.1)
        PVX2                    magicformula.Parameter = magicformula.ParameterFittable('PVX2', 0, -0.1, 0.1)
        RBX1                    magicformula.Parameter = magicformula.ParameterFittable('RBX1', 5, 5, 50)
        RBX2                    magicformula.Parameter = magicformula.ParameterFittable('RBX2', 5, 5, 50)
        RCX1                    magicformula.Parameter = magicformula.ParameterFittable('RCX1', 1, -1, 1.2)
        REX1                    magicformula.Parameter = magicformula.ParameterFittable('REX1', -1, -10, 1)
        REX2                    magicformula.Parameter = magicformula.ParameterFittable('REX2', -0.1, -5, 1)
        RHX1                    magicformula.Parameter = magicformula.ParameterFittable('RHX1')
        PTX1                    magicformula.Parameter = magicformula.ParameterFittable('PTX1')
        PTX2                    magicformula.Parameter = magicformula.ParameterFittable('PTX2')
        PTX3                    magicformula.Parameter = magicformula.ParameterFittable('PTX3')
        %% [OVERTURNING_COEFFICIENTS]
        QSX1                    magicformula.Parameter = magicformula.ParameterFittable('QSX1')
        QSX2                    magicformula.Parameter = magicformula.ParameterFittable('QSX2')
        QSX3                    magicformula.Parameter = magicformula.ParameterFittable('QSX3')
        %% [LATERAL_COEFFICIENTS]
        PCY1                    magicformula.Parameter = magicformula.ParameterFittable('PCY1', 1.9, 1.5, 2)
        PDY1                    magicformula.Parameter = magicformula.ParameterFittable('PDY1', 0.8, 0.1, 5)
        PDY2                    magicformula.Parameter = magicformula.ParameterFittable('PDY2', -0.05, -0.5, 0)
        PDY3                    magicformula.Parameter = magicformula.ParameterFittable('PDY3', 0, -10, 10)
        PEY1                    magicformula.Parameter = magicformula.ParameterFittable('PEY1', -0.8, -100, 100)
        PEY2                    magicformula.Parameter = magicformula.ParameterFittable('PEY2', -0.6, -100, 100)
        PEY3                    magicformula.Parameter = magicformula.ParameterFittable('PEY3', 0.1)
        PEY4                    magicformula.Parameter = magicformula.ParameterFittable('PEY4')
        PKY1                    magicformula.Parameter = magicformula.ParameterFittable('PKY1', -20, -100, -5)
        PKY2                    magicformula.Parameter = magicformula.ParameterFittable('PKY2', 2, -5, 5)
        PKY3                    magicformula.Parameter = magicformula.ParameterFittable('PKY3', 0, -1, 1)
        PHY1                    magicformula.Parameter = magicformula.ParameterFittable('PHY1')
        PHY2                    magicformula.Parameter = magicformula.ParameterFittable('PHY2')
        PVY1                    magicformula.Parameter = magicformula.ParameterFittable('PVY1')
        PVY2                    magicformula.Parameter = magicformula.ParameterFittable('PVY2')
        PVY3                    magicformula.Parameter = magicformula.ParameterFittable('PVY3')
        PVY4                    magicformula.Parameter = magicformula.ParameterFittable('PVY4')
        RBY1                    magicformula.Parameter = magicformula.ParameterFittable('RBY1', 5, 2, 40)
        RBY2                    magicformula.Parameter = magicformula.ParameterFittable('RBY2', 2, 2, 40)
        RBY3                    magicformula.Parameter = magicformula.ParameterFittable('RBY3', 0.02, -0.15, 0.15)
        RCY1                    magicformula.Parameter = magicformula.ParameterFittable('RCY1', 1, 0.8, 2)
        REY1                    magicformula.Parameter = magicformula.ParameterFittable('REY1', -0.1, -6, 1)
        REY2                    magicformula.Parameter = magicformula.ParameterFittable('REY2', 0.1, -1, 5)
        RHY1                    magicformula.Parameter = magicformula.ParameterFittable('RHY1')
        RHY2                    magicformula.Parameter = magicformula.ParameterFittable('RHY2')
        RVY1                    magicformula.Parameter = magicformula.ParameterFittable('RVY1')
        RVY2                    magicformula.Parameter = magicformula.ParameterFittable('RVY2')
        RVY3                    magicformula.Parameter = magicformula.ParameterFittable('RVY3')
        RVY4                    magicformula.Parameter = magicformula.ParameterFittable('RVY4')
        RVY5                    magicformula.Parameter = magicformula.ParameterFittable('RVY5')
        RVY6                    magicformula.Parameter = magicformula.ParameterFittable('RVY6')
        PHY3                    magicformula.Parameter = magicformula.ParameterFittable('PHY3')
        PTY1                    magicformula.Parameter = magicformula.ParameterFittable('PTY1')
        PTY2                    magicformula.Parameter = magicformula.ParameterFittable('PTY2')
        %% [ROLLING_COEFFICIENTS]
        QSY1                    magicformula.Parameter = magicformula.ParameterFittable('QSY1')
        QSY2                    magicformula.Parameter = magicformula.ParameterFittable('QSY2')
        QSY3                    magicformula.Parameter = magicformula.ParameterFittable('QSY3')
        QSY4                    magicformula.Parameter = magicformula.ParameterFittable('QSY4')
        %% [ALIGNING_COEFFICIENTS]
        QBZ1                    magicformula.Parameter = magicformula.ParameterFittable('QBZ1')
        QBZ2                    magicformula.Parameter = magicformula.ParameterFittable('QBZ2')
        QBZ3                    magicformula.Parameter = magicformula.ParameterFittable('QBZ3')
        QBZ4                    magicformula.Parameter = magicformula.ParameterFittable('QBZ4')
        QBZ5                    magicformula.Parameter = magicformula.ParameterFittable('QBZ5')
        QBZ9                    magicformula.Parameter = magicformula.ParameterFittable('QBZ9')
        QBZ10                   magicformula.Parameter = magicformula.ParameterFittable('QBZ10')
        QCZ1                    magicformula.Parameter = magicformula.ParameterFittable('QCZ1')
        QDZ1                    magicformula.Parameter = magicformula.ParameterFittable('QDZ1')
        QDZ2                    magicformula.Parameter = magicformula.ParameterFittable('QDZ2')
        QDZ3                    magicformula.Parameter = magicformula.ParameterFittable('QDZ3')
        QDZ4                    magicformula.Parameter = magicformula.ParameterFittable('QDZ4')
        QDZ6                    magicformula.Parameter = magicformula.ParameterFittable('QDZ6')
        QDZ7                    magicformula.Parameter = magicformula.ParameterFittable('QDZ7')
        QDZ8                    magicformula.Parameter = magicformula.ParameterFittable('QDZ8')
        QDZ9                    magicformula.Parameter = magicformula.ParameterFittable('QDZ9')
        QEZ1                    magicformula.Parameter = magicformula.ParameterFittable('QEZ1')
        QEZ2                    magicformula.Parameter = magicformula.ParameterFittable('QEZ2')
        QEZ3                    magicformula.Parameter = magicformula.ParameterFittable('QEZ3')
        QEZ4                    magicformula.Parameter = magicformula.ParameterFittable('QEZ4')
        QEZ5                    magicformula.Parameter = magicformula.ParameterFittable('QEZ5')
        QHZ1                    magicformula.Parameter = magicformula.ParameterFittable('QHZ1')
        QHZ2                    magicformula.Parameter = magicformula.ParameterFittable('QHZ2')
        QHZ3                    magicformula.Parameter = magicformula.ParameterFittable('QHZ3')
        QHZ4                    magicformula.Parameter = magicformula.ParameterFittable('QHZ4')
        SSZ1                    magicformula.Parameter = magicformula.ParameterFittable('SSZ1')
        SSZ2                    magicformula.Parameter = magicformula.ParameterFittable('SSZ2')
        SSZ3                    magicformula.Parameter = magicformula.ParameterFittable('SSZ3')
        SSZ4                    magicformula.Parameter = magicformula.ParameterFittable('SSZ4')
        QTZ1                    magicformula.Parameter = magicformula.ParameterFittable('QTZ1')
        MBELT                   magicformula.Parameter = magicformula.ParameterFittable('MBELT')
    end
end

